# Generated by Django 4.1.1 on 2022-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('carrito', 'carrito'), ('cancelado', 'cancelado'), ('comprado', 'comprado')], default='carrito', max_length=15),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
